# Generated by Django 4.2.1 on 2023-05-12 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='relations.account'),
            preserve_default=False,
        ),
    ]
